# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/ats/screening.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/ats/screening.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proto/ats/screening.proto\x12\x06\x61ts.v1\"H\n\rScreenRequest\x12\x1e\n\x16resume_path_or_content\x18\x01 \x01(\t\x12\x17\n\x0fjob_description\x18\x02 \x01(\t\"U\n\x0eScreenResponse\x12\x19\n\x11skill_match_score\x18\x01 \x01(\x01\x12\x15\n\rranking_score\x18\x02 \x01(\x01\x12\x11\n\tqualified\x18\x03 \x01(\x08\x32M\n\x12\x41IScreeningService\x12\x37\n\x06Screen\x12\x15.ats.v1.ScreenRequest\x1a\x16.ats.v1.ScreenResponseB\x1cZ\x1aresume/internal/pb/ats;atsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.ats.screening_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\032resume/internal/pb/ats;ats'
  _globals['_SCREENREQUEST']._serialized_start=37
  _globals['_SCREENREQUEST']._serialized_end=109
  _globals['_SCREENRESPONSE']._serialized_start=111
  _globals['_SCREENRESPONSE']._serialized_end=196
  _globals['_AISCREENINGSERVICE']._serialized_start=198
  _globals['_AISCREENINGSERVICE']._serialized_end=275
# @@protoc_insertion_point(module_scope)
