// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/ats/screening.proto

package ats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScreenRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ResumePathOrContent string                 `protobuf:"bytes,1,opt,name=resume_path_or_content,json=resumePathOrContent,proto3" json:"resume_path_or_content,omitempty"`
	JobDescription      string                 `protobuf:"bytes,2,opt,name=job_description,json=jobDescription,proto3" json:"job_description,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ScreenRequest) Reset() {
	*x = ScreenRequest{}
	mi := &file_proto_ats_screening_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenRequest) ProtoMessage() {}

func (x *ScreenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ats_screening_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenRequest.ProtoReflect.Descriptor instead.
func (*ScreenRequest) Descriptor() ([]byte, []int) {
	return file_proto_ats_screening_proto_rawDescGZIP(), []int{0}
}

func (x *ScreenRequest) GetResumePathOrContent() string {
	if x != nil {
		return x.ResumePathOrContent
	}
	return ""
}

func (x *ScreenRequest) GetJobDescription() string {
	if x != nil {
		return x.JobDescription
	}
	return ""
}

type ScreenResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SkillMatchScore float64                `protobuf:"fixed64,1,opt,name=skill_match_score,json=skillMatchScore,proto3" json:"skill_match_score,omitempty"`
	RankingScore    float64                `protobuf:"fixed64,2,opt,name=ranking_score,json=rankingScore,proto3" json:"ranking_score,omitempty"`
	Qualified       bool                   `protobuf:"varint,3,opt,name=qualified,proto3" json:"qualified,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ScreenResponse) Reset() {
	*x = ScreenResponse{}
	mi := &file_proto_ats_screening_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenResponse) ProtoMessage() {}

func (x *ScreenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ats_screening_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenResponse.ProtoReflect.Descriptor instead.
func (*ScreenResponse) Descriptor() ([]byte, []int) {
	return file_proto_ats_screening_proto_rawDescGZIP(), []int{1}
}

func (x *ScreenResponse) GetSkillMatchScore() float64 {
	if x != nil {
		return x.SkillMatchScore
	}
	return 0
}

func (x *ScreenResponse) GetRankingScore() float64 {
	if x != nil {
		return x.RankingScore
	}
	return 0
}

func (x *ScreenResponse) GetQualified() bool {
	if x != nil {
		return x.Qualified
	}
	return false
}

var File_proto_ats_screening_proto protoreflect.FileDescriptor

const file_proto_ats_screening_proto_rawDesc = "" +
	"\n" +
	"\x19proto/ats/screening.proto\x12\x06ats.v1\"m\n" +
	"\rScreenRequest\x123\n" +
	"\x16resume_path_or_content\x18\x01 \x01(\tR\x13resumePathOrContent\x12'\n" +
	"\x0fjob_description\x18\x02 \x01(\tR\x0ejobDescription\"\x7f\n" +
	"\x0eScreenResponse\x12*\n" +
	"\x11skill_match_score\x18\x01 \x01(\x01R\x0fskillMatchScore\x12#\n" +
	"\rranking_score\x18\x02 \x01(\x01R\frankingScore\x12\x1c\n" +
	"\tqualified\x18\x03 \x01(\bR\tqualified2M\n" +
	"\x12AIScreeningService\x127\n" +
	"\x06Screen\x12\x15.ats.v1.ScreenRequest\x1a\x16.ats.v1.ScreenResponseB\x1cZ\x1aresume/internal/pb/ats;atsb\x06proto3"

var (
	file_proto_ats_screening_proto_rawDescOnce sync.Once
	file_proto_ats_screening_proto_rawDescData []byte
)

func file_proto_ats_screening_proto_rawDescGZIP() []byte {
	file_proto_ats_screening_proto_rawDescOnce.Do(func() {
		file_proto_ats_screening_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ats_screening_proto_rawDesc), len(file_proto_ats_screening_proto_rawDesc)))
	})
	return file_proto_ats_screening_proto_rawDescData
}

var file_proto_ats_screening_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_ats_screening_proto_goTypes = []any{
	(*ScreenRequest)(nil),  // 0: ats.v1.ScreenRequest
	(*ScreenResponse)(nil), // 1: ats.v1.ScreenResponse
}
var file_proto_ats_screening_proto_depIdxs = []int32{
	0, // 0: ats.v1.AIScreeningService.Screen:input_type -> ats.v1.ScreenRequest
	1, // 1: ats.v1.AIScreeningService.Screen:output_type -> ats.v1.ScreenResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ats_screening_proto_init() }
func file_proto_ats_screening_proto_init() {
	if File_proto_ats_screening_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ats_screening_proto_rawDesc), len(file_proto_ats_screening_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ats_screening_proto_goTypes,
		DependencyIndexes: file_proto_ats_screening_proto_depIdxs,
		MessageInfos:      file_proto_ats_screening_proto_msgTypes,
	}.Build()
	File_proto_ats_screening_proto = out.File
	file_proto_ats_screening_proto_goTypes = nil
	file_proto_ats_screening_proto_depIdxs = nil
}
