// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: proto/ats/screening.proto

package ats

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIScreeningService_Screen_FullMethodName = "/ats.v1.AIScreeningService/Screen"
)

// AIScreeningServiceClient is the client API for AIScreeningService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AIScreeningService is implemented by the Python AI service; Go calls it for resume screening.
type AIScreeningServiceClient interface {
	Screen(ctx context.Context, in *ScreenRequest, opts ...grpc.CallOption) (*ScreenResponse, error)
}

type aIScreeningServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIScreeningServiceClient(cc grpc.ClientConnInterface) AIScreeningServiceClient {
	return &aIScreeningServiceClient{cc}
}

func (c *aIScreeningServiceClient) Screen(ctx context.Context, in *ScreenRequest, opts ...grpc.CallOption) (*ScreenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScreenResponse)
	err := c.cc.Invoke(ctx, AIScreeningService_Screen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIScreeningServiceServer is the server API for AIScreeningService service.
// All implementations must embed UnimplementedAIScreeningServiceServer
// for forward compatibility.
//
// AIScreeningService is implemented by the Python AI service; Go calls it for resume screening.
type AIScreeningServiceServer interface {
	Screen(context.Context, *ScreenRequest) (*ScreenResponse, error)
	mustEmbedUnimplementedAIScreeningServiceServer()
}

// UnimplementedAIScreeningServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIScreeningServiceServer struct{}

func (UnimplementedAIScreeningServiceServer) Screen(context.Context, *ScreenRequest) (*ScreenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Screen not implemented")
}
func (UnimplementedAIScreeningServiceServer) mustEmbedUnimplementedAIScreeningServiceServer() {}
func (UnimplementedAIScreeningServiceServer) testEmbeddedByValue()                            {}

// UnsafeAIScreeningServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIScreeningServiceServer will
// result in compilation errors.
type UnsafeAIScreeningServiceServer interface {
	mustEmbedUnimplementedAIScreeningServiceServer()
}

func RegisterAIScreeningServiceServer(s grpc.ServiceRegistrar, srv AIScreeningServiceServer) {
	// If the following call panics, it indicates UnimplementedAIScreeningServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIScreeningService_ServiceDesc, srv)
}

func _AIScreeningService_Screen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScreenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIScreeningServiceServer).Screen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIScreeningService_Screen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIScreeningServiceServer).Screen(ctx, req.(*ScreenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIScreeningService_ServiceDesc is the grpc.ServiceDesc for AIScreeningService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIScreeningService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ats.v1.AIScreeningService",
	HandlerType: (*AIScreeningServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Screen",
			Handler:    _AIScreeningService_Screen_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ats/screening.proto",
}
